// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://frsorazdqpbyonlhyeyf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZyc29yYXpkcXBieW9ubGh5ZXlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyNjA4MTMsImV4cCI6MjA2MzgzNjgxM30.Bjp71VnhYPaVCh-vK9JNthfHnJ9g7-Qfr7MOG5O-LCs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);